### ISSUE TITLE
ssl_accept

### ISSUE THREAD

**Issue by klacke** [klacke/yaws#215]
I got som bad vibes from some errors I saw in an error log, ssl_accept can fail with a variety
of reasons, some of them possibly the reason of various ssl attacks.
If ssl_accept fails, we die - on purpose.

I'm still a firm believer in dying on e.g emfile, enfile, but  not on these ehumm unspecified ssl accept
errors.

Opinions ?

**Comment by capflam** [comment]
Today, when the ssl_accept function returns an error, the acceptor process is killed. But Yaws still runs. I think this is the expected behavior. emfile and enfile errors suggest a system errors. So there is nothing much to do than kill the server. But ssl errors are just protocol problems, there is no reason to suspect errors at the system level.

**Comment by klacke** [comment]
But the ssl errors will endup calling exit(failaccept), thereby tearing down everything, will they not ??

**Comment by capflam** [comment]
Are you sure ?

if `ssl:transport_accept/1` returns `{error, emfile}`, `{error, enfile}` or any unexpected error, the acceptor terminates with the `failaccpect` reason. We do the same with `gen_tcp:accept/1`.
But if `ssl:ssl_accept/2` returns an error, the acceptor terminates with the `normal` reason, so Yaws should not die.

**Comment by klacke** [comment]
Sigh, I'm just daft. You're right
