### ISSUE TITLE
Several SSL servers on the same IP

### ISSUE THREAD

**Issue by ndpar** [klacke/yaws#245]
Is it possible to remove the limitation of single SSL enabled server per IP?

These days, when people are switching to and enforcing HTTPS, it would be very useful feature.

**Comment by capflam** [comment]
You can already define several SSL servers on the same IP. But, because Yaws does not support SNI (not yet), you must use the same SSL configuration for all servers.

The SNI support is quite new in Erlang and I'm working on its addition in Yaws. I am almost done but I need more time to refine the feature and to write some tests. I hope to finish it next week.

**Comment by ndpar** [comment]
Great! Thank you for your quick response.

**Comment by capflam** [comment]
After a long time, I finally found the time to add the SNI support in Yaws. So now, if you enable the SNI (disabled by default), you can have different SSL configurations for SSL servers in a same group (same IP/Port).

**Comment by ndpar** [comment]
Thank you!
