### ISSUE TITLE
List of values in Module:crashmsg/3

### ISSUE THREAD

**Issue by evbogdanov** [klacke/yaws#261]
Hello again.

When trying to implement customized `{errormod_crash, Module}`, I've bumped into strange limitation. 

It seems like `Module:crashmsg/3` doesn't support list of return values:
```
[{status, 500},
 {header, {content_type, "application/json; charset=utf-8"}},
 {html, Json}].
```

Is it bug or feature?

**Comment by leoliu** [comment]
The manual does say the function must return a tuple though. Maybe a missing feature?

**Comment by vinoski** [comment]
Based on what your example shows, if you just return

    {content, "application/json; charset=utf-8", Json}

you'll get exactly what you want, including the 500 error code since that's the default for crash messages.

**Comment by evbogdanov** [comment]
@leoliu @vinoski thank you.

I've read the manual and "Building Web Apps with Erlang". In his book, Zachary uses exactly the same `{content, MimeType, Content}` return value for generating JSON.

My example is extremely basic, I know. But in real-world scenario, that missing feature might be more meaningful, right?

And as a bonus, it would be nice to have a consistent behaviour between `out/1`, `Module:out404/3` and our guy.

**Comment by vinoski** [comment]
The issue is that in this context we're inside a crash handler. Something bad and unexpected has happened. There are things a normal `out/1` function can return, such as streaming directives, redirections, websocket directives, etc. that don't make sense in this context and could cause further errors. By limiting what can be returned from a crash handler to a simple yet useful subset, we have a much better chance of getting something meaningful back to the client.

**Comment by evbogdanov** [comment]
Good point. I guess we can close that then.
