### ISSUE TITLE
Yaws output headers in wrong order

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#377]
Try to return the following from a `out/1`:

```
out(_A) ->
    [{header, {"Test-Header", "1"}},
     {header, {"Test-Header", "2"}}].
```

and inspect the response headers in `curl` or any browser:

```
Test-Header: 2
Test-Header: 1
```

**Comment by vinoski** [comment]
This is an interesting issue, since RFC 7230 clearly states that header order is insignificant, which means we could just close this issue with no changes. However, 7230 also states that it's good practice to return control data headers first, so it certainly suggests an order, and if we're going to do that, there's no reason we can't also do our best to preserve the header order returned from `out/1`.

**Comment by leoliu** [comment]
I just tested the fix and it worked well. Thanks.
